### ISSUE TITLE
[Bug] Crossing theme wrapping issues

### ISSUE THREAD

**Issue by Cyinthia** [BlackyWhoElse/streamer.bot-actions#117]
### Describe the bug
Improper text wrapping on theme

### To Reproduce
Typing a long paragraph will do the trick on crossing theme

### Expected behavior
Text to be wrapped properly and have a curved edge at the end as well on the right side

### Screenshots

![Image](https://github.com/user-attachments/assets/d3da8abd-3905-4391-8694-91809c5584bc)

Words get cut off and is not bubbled(?) properly. It is not an asset overlapping it, I had placed it like so to make it seem like it.

### Additional context
I've tried adding margins with  "right: 15px;" which did not seem to do the trick

.content {
    background-color: var(--message-background-color);
    border-radius: 15px;
    left: 15px;
    right: 15px;
}

Did not code block it as it seems on the preview it would make it one line and potentially harder to read

**Comment by BlackyWhoElse** [comment]
Hey, thanks for raising the issue.

I checked it myself and see the problem.

Would you be so kind and check if this fixes the problem?
Note, if you edit the css, the browser source needs to be refreshed 

```css
:root {
    /** Left: row Right: row-reverse */
    --chat-align: row;
    --message-gap-bottom: 5px;
    --name-background-color: #db559b;
    --message-background-color: #fdfae2;
    --badge-size: 15px;
    --badge-spacing: 2px;
    --emote-size: 16px;
    --emote-only-size: 32px;
    --font-color: #3c3a2d;
    --font-size: 16px;
    --font-family: 'Roboto', sans-serif;
    --time-size: 12px;
    --time-align: right;
    --animate-duration: .3s;
    --animate-delay: 0;
}

body {
    font-family: var(--font-family);
    margin: 0;
    padding: 0;
}

#chat {
    height: 100vh;
    position: fixed;
    overflow: hidden;
    display: flex;
    flex-direction: column;
    width: 100vw;
    justify-content: flex-end;
    margin: 0;
    padding: 0;
}

#chat li {
    background-color: transparent;
}


.msg {
    display: flex;
    margin-bottom: var(--message-gap-bottom);
    flex-direction: var(--chat-align);
}

.badges img {
    width: var(--badge-size);
    margin-left: var(--badge-spacing);
}

.message {
    padding: var(--message-padding);
    color: var(--font-color);
    font-size: var(--font-size);
    overflow-wrap: anywhere;
    position: relative;
    width: fit-content;
}

.message div {
    padding: 6px;
    position: relative;
}

.message .emote {
    height: var(--emote-size);
}

.emoteonly .message .emote {
    height: var(--emote-only-size);
}

.name {
    color: #fff;
    font-weight: bold;
    background-color: var(--name-background-color);
    border-radius: 15px;
    width: fit-content;
    top: 5px;
    z-index: 999;
    align-items: center;
    display: flex;
}

.content {
    background-color: var(--message-background-color);
    border-radius: 15px;
    left: 15px;
    width: calc(100% - 30px) !important;
}

.time {
    font-size: var(--time-size);
    right: 10px;
    top: 5px;
    padding: 0 !important;
    text-align: right;
    position: absolute !important;
}

.broadcaster {}

.subcriber {}

.reply {}

.reward {}

.highlight {}

.me {}


```
