### ISSUE TITLE
Horizontal chat with profile picture

### ISSUE THREAD

**Issue by LiveDoEdu** [BlackyWhoElse/streamer.bot-actions#61]
A horizontal chat would be really cool. I know there are already some templates out there, but none that pull the user's profile image.

In this chat it would also be nice to add a highlight to messages with the option to highlight my message that exists on Twitch.

Example: Let's assume that the chat has a black background with some transparency and when the person rescues or highlight my message, only the person's message in the chat changes to white for example.

These are some ideas.

**Comment by BlackyWhoElse** [comment]
Could you add an example maybe. Paint image or a screenshot. 

Thanks

**Comment by EduStreamTips** [comment]
The example would be this screenshot I sent you on Discord.  When a person retrieves a highlighted message, the background that is dark turns white and the letter that is blank turns black.  I will make an example.

**Comment by LiveDoEdu** [comment]
[https://imgur.com/WPcRk4g](url)

**Comment by BlackyWhoElse** [comment]
@LiveDoEdu What should happen if the text is longer?
Should it wrap around?
Should the avatar stay on top or center?

**Comment by BlackyWhoElse** [comment]
6471e95 Added Bubble theme beta 

![grafik](https://user-images.githubusercontent.com/2930941/191002014-a4943753-cbf5-4998-a795-b0c0bfb454b1.png)

@LiveDoEdu You can alter the background colors as you like by modifying the classes
broadcaster, and highlight. These changes will not be added to the default themes because they are too specific to your stream.  

Please let me know if you encounter any issues with the theme.

Hope you like it.

**Comment by EduStreamTips** [comment]
When the text gets long, it makes a line break, and if the text is even longer, it ends in... Is it possible for the chat to be horizontal?

**Comment by BlackyWhoElse** [comment]
Horizontal like the ticker theme?

**Comment by BlackyWhoElse** [comment]
``` css
:root {
    /** Left: row Right: row-reverse */
    --chat-align: row;
    --avatar-size: 50px;
    --avatar-gap: 16px;
    --message-gap-bottom: 16px;
    --message-background-color: #18181b;
    --badge-size: 15px;
    --badge-spacing: 2px;
    --emote-size: 16px;
    --emote-only-size: 32px;
    --time-size: 12px;

    --font-color: #fff;
    --font-size: 16px;
    --font-family: 'Roboto', sans-serif;

    --spacing-right: 25px;
}

body {
    font-family: var(--font-family);
    margin: 0;
    padding: 0;
}

#chat {
    position: fixed;
    overflow: hidden;
    display: flex;
    flex-direction: row;
    width: 100vw;
    justify-content: flex-end;
    margin: 0;
    padding: 0;
    white-space: nowrap;
    height: fit-content;
}

.msg {
    display: flex;
    background-color: var(--message-background-color);
    margin-bottom: var(--message-gap-bottom);
    flex-direction: var(--chat-align);
    border-radius: 50px;
    justify-content: left;
    align-items: center;
    width: fit-content;
    margin-right: 15px;
}

.avatar img {
    width: calc(var(--avatar-size));
    border-radius: 50px;
}

.avatar {
    margin-right: 8px;
    height: var(--avatar-size);
}

.badges {
    display: none;
}

.badges img {
    width: var(--badge-size);
    margin-left: var(--badge-spacing);
}

.message {
    color: var(--font-color);
    font-size: var(--font-size);
    overflow-wrap: anywhere;
    padding: 15px 0;
}

.content {
    display: inline-block;
    padding-right: var(--spacing-right);
    text-shadow: 1px 1px black;
}

.message .emote {
    height: var(--emote-size);
}

.emoteonly .message .emote {
    height: var(--emote-only-size);
}

.name {
    color: var(--userColor);
    font-weight: bold;
}

.time {
    font-size: var(--time-size);
    color: aliceblue;
    position: absolute;
    right: var(--spacing-right);
    bottom: 2px;
}

.subscriber {}

.broadcaster {}

.reply {}

.reward {}

.highlight {}

.me {}
```
