### ISSUE TITLE
Chat Variation

### ISSUE THREAD

**Issue by pGommes** [BlackyWhoElse/streamer.bot-actions#82]
How could I create a trigger to change the style of the message, for example, if I'm a subscriber or moderator, I understand that there are variables but I couldn't apply it because I didn't have an example of their use in the HTML code.

**Comment by BlackyWhoElse** [comment]
The differenve between normal users, subs, mods and broadcasters are stored inside the {{classes}} variable.

You can find more class types here:
https://github.com/BlackyWhoElse/streamer.bot-actions/blob/69a3355e788536d3ca44c22dbb03e14e424ebadb/widget/chat/js/script.js#L105-L135

## Default Theme template
``` html
<template id="message_twitch">
  <li id="{{msgId}}" class="{{classes}}" style="--userColor:{{color}}">
    <div class="avatar">
      <img src="{{avatar}}" />
    </div>
    <div class="message">
      <span class="badges">{{badges}}</span>
      <span class="name">{{displayName}}</span>
      <div class="content">{{message}}</div>
      <div class="time">{{time}}</div>
    </div>
  </li>
</template>
```


## Example Message
``` html
<li id="32d8db00-bef1-44cf-b66f-fa651c5d237c" class="msg subscriber broadcaster animate__animated animate__bounceInRight" style="--userColor:#FF0000">
    <div class="avatar">
      <img src="https://static-cdn.jtvnw.net/jtv_user_pictures/a88dd690-f653-435e-ae3f-cd312ee5b736-profile_image-300x300.png">
    </div>
    <div class="message">
      <span class="badges">
         <img class="broadcaster" title="broadcaster" src="https://static-cdn.jtvnw.net/badges/v1/5527c58c-fb7d-422d-b71b-f309dcb85cc1/3"><img class="subscriber" title="subscriber" src="https://static-cdn.jtvnw.net/badges/v1/31966bdb-b183-47a9-a691-7d50b276fc3a/3">  
      </span>    
      <span class="name">Blackywersonst</span>  
      <div class="content">Hello Wolrd</div>  
      <div class="time">9:15</div>  
    </div>
  </li>
```

**Comment by pGommes** [comment]
Sorry for my stupidity, but what would I have to do to make it work to create another <template id="message_twitch">?</template> another index.hml another themplate.hml

![image](https://github.com/BlackyWhoElse/streamer.bot-actions/assets/29603439/4a518b61-fa78-4f56-ac77-44bd8a0fb1ad)
****

**Comment by BlackyWhoElse** [comment]
Mh not sure what exactly you want to do. But if you want to have a custom template for mods or subs, that's not possible right now. The only changes you can make are through a css class.

The different templates you see there are just there to support different types of messages, like a youtube message and channel rewards.

They are the "structure" of each message.
You could do something like:

``` css
.subscriber {
    color: #fff;
    background color: green;
}

.moderator {
    color: #18181b;
    background-color: red;
}

.reply {
    color: #18181b;
    background-color: aqua;
}

.highlight {
    color: #fff;
    background-color: purple;
}
```

It all depends on your HTML and CSS skills.
I will sometimes help if the theme you want is easy to create.

So if you have an image that can better describe your theme, I might be willing to create it for you.

**Comment by pGommes** [comment]
From what I understand, the subscriber variables, for example, if called correctly, can pull different css configurations, that's what I'm trying to execute but without knowing where to go, unfortunately I'm a layman on the subject. I took some screenshots that better exemplify what I'm trying to do.

![Screenshot_3](https://github.com/BlackyWhoElse/streamer.bot-actions/assets/29603439/2581524a-ffcb-482d-976f-8bb11dadebe5)
![Screenshot_4](https://github.com/BlackyWhoElse/streamer.bot-actions/assets/29603439/f2152b68-cdc5-4082-aefa-2d9bc56b91b3)

My chat

![Screenshot_5](https://github.com/BlackyWhoElse/streamer.bot-actions/assets/29603439/189d6340-64eb-4c68-8bf6-348f6384ac50)

broadcaster and moderator

**Comment by BlackyWhoElse** [comment]
Ohhhh I remeber Edu i did this bubble theme for him.  

So you are using the bubble theme and want to alter the background of broadcaster and moderator is that correct? 

Just add the #chat li selector to your example

```css
#chat li.broadcaster {
    background-color: #ff000073;
    border: 1px solid var(--message-background-color);
}

#chat li.moderator{
   background-color: #6dff0073;
    border: 1px solid var(--message-background-color);

}

```
